# Generated by Django 2.1.7 on 2019-03-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'StatusHHHH post', 'verbose_name_plural': 'Statuss post'},
        ),
    ]
